---
- name: "{{ epics_modules[item].name }} | Fix configure/RELEASE to include RELEASE.local"
  ansible.builtin.lineinfile:
    path: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/configure/RELEASE"
    search_string: '-include $(TOP)/RELEASE.local'
    line: '-include $(TOP)/../RELEASE.local'
  become: true

- name: "{{ epics_modules[item].name }} | Fix example IOC configure/RELEASE to include RELEASE.local"
  ansible.builtin.lineinfile:
    path: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/iocs/simDetectorIOC/configure/RELEASE"
    search_string: '-include $(TOP)/RELEASE.local'
    line: '-include $(TOP)/../RELEASE.local'
  become: true

- name: "{{ epics_modules[item].name }} | Make example IOC include ADCORE/configure/CONFIG_SITE"
  ansible.builtin.lineinfile:
    path: "{{ epics_install_path }}/{{ item }}-{{ epics_modules[item].version }}/iocs/simDetectorIOC/configure/CONFIG_SITE"
    line: '-include $(ADCORE)/configure/CONFIG_SITE'
  become: true
