---
- name: Clear global rebuild flag
  ansible.builtin.file:
    path: "{{ epics_install_path }}/.flag/REBUILD"
    state: absent
  become: true

- name: Build EPICS Modules
  include_tasks: build_module.yml
  loop: "{{ epics_modules_list }}"
  when: item != 'skip'

- name: "Copy .bob files under {{ epics_install_path }} to {{ opi_install_path }}"
  ansible.builtin.shell:
    cmd: "find {{ epics_install_path }} -name '*.bob' -exec cp {} {{ opi_install_path }}/ \\;"
  become: true
