# this assumes root disk device is /dev/sda override on command line if not
root_disk: sda
root_partition: "{{ ansible_mounts|json_query('[?mount == `/`].device') | first }}"
root_fs_type: "{{ ansible_mounts|json_query('[?mount == `/`].fstype') | first }}"
partitions: "{{ ansible_devices[root_disk].partitions.keys() | list | sort }}"
last_partition_no: "{{ ansible_devices[root_disk].partitions.keys() | list | length }}"
