# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  # docs at https://docs.vagrantup.com.

  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  require_relative 'common'

  @distros.each do |distro|

    # dont't create this VM unless the distro has been selected for creation
    if @distro_names.include?(distro[:name]) or @distro_names.include?("all")
      print "processing #{distro[:name]} #{distro} ...\n"
    else
      print "skipping '#{distro[:name]}'\n"
      next
    end

    config.vm.define distro[:name] do |this|

      # resize the original base image disk size
      this.vm.disk :disk, size: "150GB", primary: true

      this.vm.synced_folder ".", "/vagrant", disabled: true
      this.vm.synced_folder "../ansible", "/ansible"

      this.vm.box = distro[:box]
      this.vm.hostname = distro[:name]

      this.vm.provider "virtualbox" do |vb|
        vb.name = "epics-training-" + distro[:name]
        vb.gui = true
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--cpus", @cpus]
        vb.customize ["modifyvm", :id, "--vram", "256"]
        # vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
        vb.memory = "4096"
      end

      # Install and run guest-side Ansible
      install_script = File.read("../initial_setup.sh")
      this.vm.provision "shell" do |s|
        s.inline = install_script
        s.env = { ansible_args: @ansible_args, installer: distro[:installer] }
      end
    end
  end
end
