# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "local" do |local|
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    # start with official Rocky Linux 9 box
    # local.vm.box = "rockylinux/9"
    local.vm.box = "generic/rocky9"
    # resize the original base image disk size
    local.vm.disk :disk, size: "150GB", primary: true

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # local.vm.network "private_network", ip: "192.168.33.10"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    # local.vm.network "public_network"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # local.vm.synced_folder "../data", "/vagrant_data"

    # Disable the default share of the current code directory. Doing this
    # provides improved isolation between the vagrant box and your host
    # by making sure your Vagrantfile isn't accessible to the vagrant box.
    # If you use this you may want to enable additional shared subfolders as
    # shown above.
    local.vm.synced_folder ".", "/vagrant", disabled: true

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # in this case for VirtualBox:
    local.vm.provider "virtualbox" do |vb|
      vb.name = "epics-training"
      vb.gui = true
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--vram", "256"]
      vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      vb.memory = "4096"
    end
    #
    # View the documentation for the provider you are using for more
    # information on available options.

    # Provisioning with a shell script.
    #
    # TODO - this should be ansible but should not get used by the default
    # playbook so as not to interfere with the original, manual
    # 'install from scratch' instructions.
    local.vm.provision "shell", inline: <<-SHELL
      # installs from manual instructions
      dnf install -y epel-release
      dnf update -y --refresh
      dnf install -y dkms kernel-devel kernel-headers

      # install gnome desktop
      dnf group install -y "Development Tools"
      dnf group install -y "Workstation"
      systemctl set-default graphical

      # add a user for the EPICS developer
      adduser epics-dev -c"EPICS Developer" -p ""
      sed -i '/epics-dev/d' /etc/sudoers
      bash -c "echo 'epics-dev    ALL=(ALL)      NOPASSWD: ALL'  >> /etc/sudoers"
    SHELL

    # Provisioning with Ansible.
    local.vm.provision "ansible" do |ansible|
      ansible.playbook = "../ansible/playbook.yml"
    end
  end
end
