---
- name: Create installation directories
  file:
    path: "{{item}}"
    state: directory
    mode: "0755"
  become: true
  loop:
    - "{{ epics_install_path }}"
    - "{{ epics_install_path }}/RELEASE.local.d"
    - "{{ epics_install_path }}/epics-tools.sh.d"
    - "{{ epics_install_path }}/.flag"
    - "{{ opi_install_path }}"

- name: gather facts especially cpu cores
  ansible.builtin.setup:
