---
- name: Check distro has been identified
  ansible.builtin.assert:
    that:
      - is_debian or is_redhat
    fail_msg: "Unkown distro {{ ansible_distribution }}"

- name: Install common packages
  dnf:
    name: ["gcc-c++"]
    state: latest
    update_cache: true
  become: true
  when: is_redhat

- name: Create installation directories
  file:
    path: "{{item}}"
    state: directory
    mode: "0755"
  become: true
  loop:
    - "{{ epics_install_path }}"
    - "{{ epics_install_path }}/RELEASE.local.d"
    - "{{ epics_install_path }}/epics-tools.sh.d"
    - "{{ epics_install_path }}/.flag"
    - "{{ opi_install_path }}"

- name: gather facts especially cpu cores
  ansible.builtin.setup:
