---
- name: Install common packages
  dnf: 
    name: ['gcc-c++']
    state: latest
    update_cache: true
  become: true

- name: Create installation directories
  file:
    path: "{{item}}"
    state: directory
    mode: '0755'
  become: true
  loop:
    - "{{epics_install_path}}"
    - "{{epics_install_path}}/RELEASE.local.d"
    - "{{epics_install_path}}/.flag"

