---
# tasks file for epics_tools_libs_jvm

# Install open jdk 17
- name: ensure jvm directory exists for jdk-17
  file:
    path: /opt/epics-tools/lib/jvm/jdk-17
    state: directory
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

- name: install open jdk 17
  ansible.builtin.unarchive:
    src: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
    dest: /opt/epics-tools/lib/jvm/jdk-17
    remote_src: yes
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"
    extra_opts:
    - --strip-components=1

# Install open maven
- name: ensure mvn directory exists for mvn
  file:
    path: /opt/epics-tools/lib/apache-maven-3.6.0
    state: directory
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

- name: install apache-maven-3.6.0
  ansible.builtin.unarchive:
    src: https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
    dest: /opt/epics-tools/lib/apache-maven-3.6.0
    remote_src: yes
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"
    extra_opts:
    - --strip-components=1
