---
# tasks file for epics_tools_libs_jvm

# Install open jdk
- name: ensure java_home directory exists
  become: true
  file:
    path: "{{ java_home }}"
    state: directory
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

- name: Check if Java installation exists
  stat:
    path: "{{ java_home }}/bin/java"
  register: java_installation
  changed_when: false

- name: install open jdk 17
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.10%2B7/OpenJDK17U-jdk_x64_linux_hotspot_17.0.10_7.tar.gz
    dest: "{{ java_home }}"
    remote_src: yes
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"
    extra_opts:
    - --strip-components=1
  when: java_installation.stat.exists == false

# Install open maven
- name: ensure mvn directory exists
  become: true
  file:
    path: "{{ mvn_home }}"
    state: directory
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"

- name: Check if Maven installation exists
  stat:
    path: "{{ mvn_home }}/bin/mvn"
  register: mvn_installation
  changed_when: false

- name: install apache-maven-3.6.0
  become: true
  ansible.builtin.unarchive:
    src: https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
    dest: "{{ mvn_home }}"
    remote_src: yes
    owner:  "{{ epics_services_account }}"
    group:  "{{ epics_services_account }}"
    extra_opts:
    - --strip-components=1
  when: mvn_installation.stat.exists == false

# Configure proxies for maven
- name: clear existing proxy configuration
  become: true
  community.general.xml:
    path: "{{ mvn_home }}/conf/settings.xml"
    namespaces:
      mvn: http://maven.apache.org/SETTINGS/1.0.0
    xpath: /mvn:settings/mvn:proxies
    set_children: []
  when: proxy_mvn is defined

- name: add proxy configuration
  become: true
  community.general.xml:
    path: "{{ mvn_home }}/conf/settings.xml"
    namespaces:
      mvn: http://maven.apache.org/SETTINGS/1.0.0
    xpath: /mvn:settings/mvn:proxies
    add_children: "{{ item }}"
    input_type: xml
    pretty_print: true
  loop: "{{ proxy_mvn }}"
  when: proxy_mvn is defined
