---
# busy-1.7.4's busyRecord.c declares its dset functions as plain DEVSUPFUN
# Downgrade it to warning and use gnu17 standard to make it compile
- name: "{{ module.name }} pre-build hook | Allow legacy untyped DEVSUPFUN casts"
  ansible.builtin.blockinfile:
    path: "{{ epics_install_path }}/{{ module.id }}-{{ module.version }}/configure/CONFIG_SITE"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      USR_CFLAGS_Linux += -std=gnu17 -Wno-error=incompatible-pointer-types
  become: true
