# Default configuration for the available roles

# minimal defaults for fast testing - copy local.yml.sample or everything.yml
# to local.yml and adjust as needed
initial_setup: false
docker: true # for rootful this needs to happen before first reboot
epics_modules_build: false
catrust: false
epics_tools: false
bluesky: false

# Default configuration for the EPICS modules to build
epics_modules_list:
  - base
  - pvxs

# Default: false proxy
proxy_env: {}

# when building inside a container during CI this is set to true
in_container: false
