# Default configuration for the available roles
initial_setup: false
docker: true # for rootful this needs to happen before first reboot
epics_modules: true
catrust: false
epics_tools: true
bluesky: false

# Default configuration for the EPICS modules to build
epics_modules_list:
  - base
  - pvxs
  - p4p
  - asyn
  - seq
  - opcua
  - autosave
  - busy
  - sscan
  - calc
  - adcore
  - adsimdetector
  - adpvadriver

# Default: no proxy
proxy_env: {}
