# Default configuration for the available roles
epics_modules: true
catrust: false

# Default configuration for the EPICS modules to build
epics_modules_list:
#  - base
#  - pvxs
#  - seq
#  - asyn
#  - adcore
#  - adsimdetector

# Default: no proxy
proxy_env: {}
