# Default configuration for the available roles
epics_modules: true
catrust: false
epics_tools: true
docker: true
bluesky: true

# Default configuration for the EPICS modules to build
epics_modules_list:
  - base
  - pvxs

# Default: no proxy
proxy_env: {}
