# A configuration to be copied to local.yml when running CI
# It has a few differences from everything.yml (see comments inline)
#
# For use by CI running in containers

epics_modules_build: true
catrust: false
epics_tools: true
docker: true
# the attempt to make docker outside docker work is a failure because the
# compose file tries to mount host folders it cannot see. For the moment
# disable buesky build in CI
bluesky: false

# List the EPICS modules that will be built in this order (base is mandatory)
epics_modules_list:
  - base
  - pvxs
  # Two alternative Python wrappers
  - p4p
  # pvapy does not like python 3.12, debian has boost version issues
  - "{{ 'pvapy' if ansible_distribution == 'Rocky' else 'skip' }}"
  - seq
  - asyn
  - opcua
  # AreaDetector dependencies
  - autosave
  - busy
  - sscan
  - calc
  # Fedora xmllib2 is too new for (ADCore missing XmlGetGlobal)
  # debian has too early a version of ansible to accept search_string in lineinfile
  - "{{ 'adcore' if ansible_distribution in ['Ubuntu', 'Rocky'] else 'skip' }}"
  - "{{ 'adsimdetector' if ansible_distribution in ['Ubuntu', 'Rocky'] else 'skip' }}"
  # only build if we built pvapy
  - "{{ 'adpvadriver' if ansible_distribution == 'Rocky' else 'skip' }}"

# tell ansible that we are in a container instead of VM
in_container: true
