---
# Install MariaDB; configure for Archiver Appliance
- name: Install required DEB dependencies
  become: true
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    update_cache: true
    state: present
  when: is_debian

- name: Install required RPM dependencies
  become: true
  ansible.builtin.dnf:
    name: mariadb-server
    update_cache: true
    state: present
  when: is_redhat

- name: Manage MariaDB service; create AA user and database
  become: true
  when: not in_container
  block: 
    - name: Manage MariaDB service
      ansible.builtin.systemd_service:
        name: mariadb
        state: started
        enabled: true

    - name: MariaDB - create Archiver-Appliance database
      community.mysql.mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: archappl

    - name: MariaDB - create Archiver-Appliance user
      community.mysql.mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: archappl
        password: archappl
        priv: 'archappl.*:ALL'
        state: present
