- name: Add TCP and UDP protocols
  firewalld:
    zone: public
    permanent: yes
    state: enabled
    immediate: yes
    protocol: "{{ item }}"
    offline: false
  loop:
    - tcp
    - udp
  become: yes

- name: tcp ports facts
  community.general.listen_ports_facts:

- name: Add ports to firewall
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    immediate: true
    permanent: true
    offline: false
  loop: "{{ ansible_facts.tcp_listen  | map(attribute='port') | sort | list }}"
  register: ports_added_to_firewalld
  become: yes

- name: print Ports Added
  debug:
    var: ports_added_to_firewalld

- name: tcp ports facts
  community.general.listen_ports_facts:

- name: Add ports to firewall
  firewalld:
    port: "{{ item }}/udp"
    state: enabled
    immediate: true
    permanent: true
    offline: false
  loop: "{{ ansible_facts.tcp_listen  | map(attribute='port') | sort | list }}"
  register: ports_added_to_firewalld
  become: yes
