---
- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: Install Dev Tools and Gnome
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - vim
      - curl
      - ansible
      - gnome-core
  become: yes

- name: Change default target to graphical.target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  become: yes

- name: create user
  ansible.builtin.user:
    name: "{{ dev_user }}"
    shell: /bin/bash
    createhome: yes
    password: ""
    comment: "EPICS Developer"
  become: yes

- name: Make users passwordless for sudo in group wheel
  lineinfile:
    path: /etc/sudoers
    regexp: "^%{{ dev_user }}"
    line: "%{{ dev_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: yes
