---
- name: Upgrade all packages
  ansible.builtin.apt module:
    name: "*"
    state: latest
  become: yes

- name: Install Development Tools
  ansible.builtin.apt module:
    name:
      - dkms
      - kernel-devel
      - kernel-headers
      - build-essential
      - vannila-gnome-desktop
      - vannila-gnome-default-settings
  become: yes

- name: Change default target to graphical.target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  become: yes

- name: create user
  ansible.builtin.user:
    name: "epics-dev"
    shell: /bin/bash
    createhome: yes
    groups: wheel
    password: ""
    comment: "EPICS Developer"
  become: yes

- name: Make users passwordless for sudo in group wheel
  lineinfile:
    path: /etc/sudoers
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: yes

- name: remove services that fail in virtualbox - mcelog
  ansible.builtin.systemd:
    name: mcelog
    state: stopped
    enabled: no
  become: yes

- name: remove services that fail in virtualbox - systemd-vconsole
  ansible.builtin.systemd:
    name: systemd-vconsole-setup
    state: stopped
    enabled: no
  become: yes
