---
- name: Validate the partition variables
  ansible.builtin.debug:
    msg: "rootdisk:{{ root_disk }}, root_part:{{ root_partition }} fs_type:{{ root_fs_type }}, all_partitions:{{ partitions }}, no:{{ last_partition_no }}"

- name: Install growpart
  ansible.builtin.apt:
    name: cloud-guest-utils
  become: true
  when: is_debian

- name: Install growpart
  dnf:
    name: cloud-utils-growpart
  become: true
  when: is_redhat

- name: growpart the root partition to fill all available space
  ansible.builtin.shell:
    cmd: "growpart /dev/{{ root_disk }} {{ last_partition_no }}"
  become: true
  # growpart fails if the partition is already grown
  ignore_errors: true

- name: Grow xfs root filesystem to fill all available space
  ansible.builtin.shell:
    cmd: xfs_growfs {{ root_partition }}
  when: root_fs_type == 'xfs'
  become: true

- name: Grow btrfs root filesystem to fill all available space
  ansible.builtin.shell:
    cmd: btrfs filesystem resize 1:max /
  when: root_fs_type == 'btrfs'
  become: true

- name: APT Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true
  when: is_debian

- name: RPM Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  when: is_redhat

- name: APT Install Dev Tools and Gnome
  ansible.builtin.apt:
    name:
      - build-essential
      - git
      - vim
      - curl
      - gnome-core
  become: true
  when: is_debian

- name: RPM Install Development Tools
  dnf:
    name:
      - "@Development Tools"
      - git
      - vim
      - curl
      # TODO break out the distro specific differences into common/vars/main.yml
      - "@{{ 'Fedora ' if ansible_distribution == 'Fedora' }}Workstation"
  become: true
  when: is_redhat

- name: Change default target to graphical.target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  become: true

# does not seem to work and the location of gdm config is different in different distros
# - name: Make XOrg the default display manager
#   ansible.builtin.lineinfile:
#     path: "{{ gdm_config }}"
#     search_string: "DefaultSession"
#     line: "DefaultSession=gnome-xorg.desktop"
#   become: true

- name: create user
  ansible.builtin.user:
    name: "{{ dev_user }}"
    shell: /bin/bash
    createhome: true
    password: ""
    comment: "EPICS Developer"
  become: true

- name: Make users passwordless for sudo in group wheel
  lineinfile:
    path: /etc/sudoers
    regexp: "^%{{ dev_user }}"
    line: "%{{ dev_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: true
