epics_modules:
  
  base:
    name: "EPICS Base"
    version: "7.0.8"
    url: "https://epics-controls.org/download/base/base-7.0.8.tar.gz"
    release_var: "EPICS_BASE"
    release_sortkey: "99"
    required_rpms:
      - readline-devel
      - ncurses-devel
      - glibc-devel
      - perl
      - perl-devel
      - perl-Test-Simple
      - perl-Test-Harness

  pvxs:
    name: "PXVS"
    version: "1.3.1"
    url: "https://github.com/mdavidsaver/pvxs/archive/refs/tags/1.3.1.tar.gz"
    release_var: "PVXS"
    release_sortkey: "10"
    required_rpms:
      - libevent-devel

  seq:
    name: "SNL Sequencer"
    version: "2.2.9"
    url: "https://github.com/epics-modules/sequencer/archive/refs/tags/R2-2-9.tar.gz"
    release_var: "SNLSEQ"
    release_sortkey: "10"
    required_rpms:
      - re2c
