epics_modules:

  base:
    name: "EPICS Base"
    version: "7.0.8"
    url: "https://epics-controls.org/download/base/base-7.0.8.tar.gz"
    release_var: "EPICS_BASE"
    release_sortkey: "99"
    required_rpms:
      - readline-devel
      - ncurses-devel
      - glibc-devel
      - perl
      - perl-devel
      - perl-Test-Simple
      - perl-Test-Harness

  pvxs:
    name: "PXVS"
    version: "1.3.1"
    url: "https://github.com/mdavidsaver/pvxs/archive/refs/tags/1.3.1.tar.gz"
    release_var: "PVXS"
    release_sortkey: "10"
    required_rpms:
      - libevent-devel

  seq:
    name: "SNL Sequencer"
    version: "2.2.9"
    url: "https://github.com/epics-modules/sequencer/archive/refs/tags/R2-2-9.tar.gz"
    release_var: "SNCSEQ"
    release_sortkey: "10"
    required_rpms:
      - re2c

  asyn:
    name: "ASYN"
    version: "4.44.2"
    url: "https://github.com/epics-modules/asyn/archive/refs/tags/R4-44-2.tar.gz"
    release_var: "ASYN"
    release_sortkey: "10"
    required_rpms:
      - rpcgen
      - libtirpc-devel
    enable_repos:
      - crb
    pre_hook: asyn_prep.yml

  autosave:
    name: "autoSaveRestore"
    version: "5.11"
    url: "https://github.com/epics-modules/autosave/archive/refs/tags/R5-11.tar.gz"
    release_var:  "AUTOSAVE"
    release_sortkey: "10"

  busy:
    name: "Busy Record"
    version: "1.7.4"
    url: "https://github.com/epics-modules/busy/archive/refs/tags/R1-7-4.tar.gz"
    release_var: "BUSY"
    release_sortkey: "10"

  sscan:
    name: "SScan module"
    version: "2.11.6"
    url: "https://github.com/epics-modules/sscan/archive/refs/tags/R2-11-6.tar.gz"
    release_var: "SSCAN"
    release_sortkey: "10"

  calc:
    name: "Calc module (misc records)"
    version: "3.7.5"
    url: "https://github.com/epics-modules/calc/archive/refs/tags/R3-7-5.tar.gz"
    release_var: "CALC"
    release_sortkey: "10"

  adcore:
    name: "AreaDetector - Core"
    version: "3.13"
    url: "https://github.com/areaDetector/ADCore/archive/refs/tags/R3-13.tar.gz"
    release_var: "ADCORE"
    release_sortkey: "10"
    required_rpms:
      - zlib-devel
      - libxml2-devel
      - libtiff-devel
      - libjpeg-devel
    pre_hook: adcore_prep.yml

  adsimdetector:
    name: "AreaDetector - SimDetector"
    version: "2.10"
    url: "https://github.com/areaDetector/ADSimDetector/archive/refs/tags/R2-10.tar.gz"
    release_var: "ADSIMDETECTOR"
    release_sortkey: "10"
    pre_hook: adsimdetector_prep.yml
