---
- name: Determine the current user
  command: whoami
  register: whoami
  become: no

- name: Add Docker GPG Key
  shell: "dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: Install Docker 1.28.6
  dnf:
    name: docker-ce-3:19.03.15-3.el9
    state: latest
    update_cache: yes
    allow_downgrade: yes

- name: Install Docker Module for Python
  pip:
    name: docker==6.1.3

- name: Install Docker Compose
  dnf:
    name: docker-compose
    state: present

- name: Add current user to the docker group
  ansible.builtin.user:
    name: "{{ whoami.stdout }}"
    groups: docker
    append: yes
