---
- name: Install Python 3
  dnf:
    name: python3
    state: present
  become: yes

- name: Install podman docker
  dnf:
    name: podman-docker
    state: present
  become: yes

- name: Install pip3
  dnf:
    name: python3-pip
    state: present
  become: yes

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present

- name: Install Podman Compose
  pip:
    name: podman-compose
    state: present

- name: Start and enable podman
  ansible.builtin.systemd:
    name: podman
    state: started
    enabled: yes
  become: yes

- name: enable podman-restart
  ansible.builtin.systemd:
    name: podman-restart
    state: started
    enabled: yes
  become: yes
