---
- name: Install Python 3
  dnf:
    name: python3
    state: present
  become: yes
- name: Install podman docker
  dnf:
    name: podman-docker
    state: present
  become: yes
- name: Install pip3
  dnf:
    name: python3-pip
    state: present
  become: yes

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present

- name: Install Podman Compose
  pip:
    name: podman-compose
    state: present

- name: Start and enable podman
  ansible.builtin.systemd:
    name: podman
    state: started
    enabled: yes

- name: enable podman-restart
  ansible.builtin.systemd:
    name: podman-restart
    state: started
    enabled: yes

- name: set alias to docker
  command: echo "alias docker=podman" > "{{ lookup('env','HOME') }}/.bashrc"

- name: Add TCP and UDP protocols
  firewalld:
    zone: public
    permanent: yes
    state: enabled
    immediate: yes
    protocol: "{{ item }}"
  loop:
    - tcp
    - udp

- name: tcp ports facts
  community.general.listen_ports_facts: 

- name: Add ports to firewall
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    immediate: true
    permanent: true
  loop: "{{ ansible_facts.tcp_listen  | map(attribute='port') | sort | list }}"
  register: ports_added_to_firewalld

- name: print Ports Added
  debug:
    var: ports_added_to_firewalld

- name: tcp ports facts
  community.general.listen_ports_facts: 

- name: Add ports to firewall
  firewalld:
    port: "{{ item }}/udp"
    state: enabled
    immediate: true
    permanent: true
  loop: "{{ ansible_facts.tcp_listen  | map(attribute='port') | sort | list }}"
  register: ports_added_to_firewalld
