---
- name: Install Python 3
  dnf:
    name: python3
    state: present
  become: yes

- name: Install pip3
  dnf:
    name: python3-pip
    state: present
  become: yes

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: present
- name: Install Podman Compose
  pip:
    name: podman-compose
    state: present

- name: Start and enable Docker serve
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
