---
- name: Install RPM prerequisites
  dnf:
    name:
      - podman-docker
      - python3-pip
    state: present
  become: yes

- name: Install PIP prerequisites
  pip:
    name: podman-compose
    state: present

- name: Start and enable podman
  ansible.builtin.systemd:
    name: podman
    state: started
    enabled: yes
  become: yes

- name: enable podman-restart
  ansible.builtin.systemd:
    name: podman-restart
    state: started
    enabled: yes
  become: yes
