---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
  become: yes

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
  become: yes

- name: Install Podman and Docker Compose
  ansible.builtin.apt:
    name:
      - podman
      - docker-compose-plugin
    state: present
  become: yes

# linger allows us to set up rootless podman daemons
- name: Check epics-dev for lingering
  include_tasks:
    file: linger.yml
  with_items: epics-dev

- name: Start and enable podman
  ansible.builtin.systemd:
    name: podman
    state: started
    enabled: yes
    scope: user

- name: Create /etc/containers/nodocker to quiet warning message
  ansible.builtin.file:
    path: /etc/containers/nodocker
    state: touch
    modification_time: preserve
    access_time: preserve
  become: yes

- name: quiet compose warning
  lineinfile:
    path: /usr/share/containers/containers.conf
    regexp: ".*compose_warning_logs.*"
    line: "compose_warning_logs = true"
  become: yes
