---
- name: Determine the current user
  command: whoami
  register: whoami
  become: no

- name: Add Docker GPG Key
  dnf_key:
    url: https://download.docker.com/linux/fedora/gpg
    state: present

- name: Add Docker Repository
  dnf_repository:
    name: docker-ce
    baseurl: https://download.docker.com/linux/fedora/32/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/fedora/gpg
    enabled: yes

- name: Install Docker 1.28.6
  dnf:
    name: docker-ce-3:19.03.15-3.fc32
    state: latest
    update_cache: yes
    allow_downgrade: yes

- name: Install Docker Module for Python
  pip:
    name: docker==6.1.3

- name: Install Docker Compose
  dnf:
    name: docker-compose
    state: present

- name: Add current user to the docker group
  ansible.builtin.user:
    name: "{{ whoami.stdout }}"
    groups: docker
    append: yes
