---
- name: Install RPM prerequisites
  dnf:
    name:
      - podman-docker
      - python3-pip
    state: present
  become: yes

- name: Install PIP prerequisites
  pip:
    name: podman-compose
    state: present

- name: Start and enable podman
  ansible.builtin.systemd:
    name: podman
    state: started
    enabled: yes
  become: yes

- name: enable podman-restart
  ansible.builtin.systemd:
    name: podman-restart
    state: started
    enabled: yes
  become: yes

- name: Create /etc/containers/nodocker to quiet warning message
  ansible.builtin.file:
    path: /etc/containers/nodocker
    state: touch
    modification_time: preserve
    access_time: preserve
  become: yes

- name: quiet compose warning
  lineinfile:
    path: /usr/share/containers/containers.conf
    regexp: ".*compose_warning_logs.*"
    line: "compose_warning_logs = true"
  become: yes
