---
- name: Set up training VM
  hosts: local

  roles:
    - role: initial_setup
      tags: initial_setup
      when: initial_setup

    - role: catrust
      tags: catrust
      when: catrust

    - role: common #  <- mandatory
      tags: common

    - role: docker
      tags: docker
      when: docker

    - role: bluesky
      tags: bluesky
      when: bluesky
      become: true
      become_user: "{{ dev_user}}"

    - role: epics-modules
      tags: epics_modules
      when: epics_modules_build

    - role: epics-tools
      tags: epics_tools
      when: epics_tools

  environment: "{{ proxy_env }}"
