name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    strategy:
      fail-fast: false
      matrix:
        distro: [rocky, debian, ubuntu, fedora]
    runs-on: ubuntu-latest

    steps:
      - name: install Vagrant and VirtualBox
        run: |
          sudo wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg &&
          sudo echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list &&
          sudo apt-get update &&
          sudo apt-get install vagrant qemu-kvm virtinst libvirt-daemon virt-manager libvirt-daemon-system libvirt-clients bridge-utils -y

      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        env:
          VAGRANT_VM_BOX: ${{ matrix.distros }}
          VAGRANT_VM_GUI: "false"
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: |
          cd .github/vagrant
          vagrant up --provider=libvirt

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello epics developer!'"
