name: CI

on:
  push:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  docker_build:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_docker_build.yml
