name: CI

on:
  push:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  vagrant:
    needs: check
    if: needs.check.outputs.branch-pr == ''
    uses: ./.github/workflows/_vagrant_up.yml
