name: "Test Roles: EPICS Modules"

on:
  push:
    paths:
      - '.github/workflows/test-roles-modules.yml'
      - 'ansible/vars/ci-*.yml'
      - 'ansible/playbook.yml'
      - 'ansible/requirements.yml'
      - 'ansible/roles/m_*/**'
      - '!ansible/roles/m_base/**'
  pull_request:
    paths:
    - '.github/workflows/test-roles-modules.yml'
    - 'ansible/vars/ci-*.yml'
    - 'ansible/playbook.yml'
    - 'ansible/requirements.yml'
    - 'ansible/roles/m_*/**'
    - '!ansible/roles/m_base/**'
  workflow_dispatch:

permissions: {}

jobs:
  check:
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/_check.yml

  resolve:
    needs: check
    permissions:
      actions: read
    uses: ./.github/workflows/_resolve_build_run.yml
    with:
      workflow_file: "build-cloud-init-images.yml"
      sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}

  test:
    needs: [check, resolve]
    name: "${{ matrix.distro }}: ${{ matrix.conf.name }}"
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu, rocky, debian, fedora]
        conf:
          - name: "EPICS Modules"
            id: "ci-modules"
    runs-on: ubuntu-latest
    timeout-minutes: 75
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false

      - name: Install QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Download qcow2 artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: training-vm-${{ matrix.distro }}-qcow2
          path: /tmp/qcow2
          run-id: ${{ needs.resolve.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Ansible in QEMU (${{ matrix.conf.name }}, source=${{ needs.resolve.outputs.source }})
        run: |
          ./cloud-init/run_ansible_test.sh \
            -i /tmp/qcow2/${{ matrix.distro }}.qcow2 \
            -c ${{ matrix.conf.id }}
